###############################
# README File for Assignment01
# Johannes Schulz-Knappe and Md Mujahedul Islam 
# 24.02.2016
###############################

We have used two seperate example datasets pre installed in R. I (Md Mujahedul Islam) have analysed "USArrests" datasets while Johannes Schulz-Knappe has used stock dataset. We created our repository called "Assignment01" on February 15 for our first pair assignment. This README files aim to clearly describe what we have done for this assignments. 

#Stock DATASET by Johannes Schulz-Knappe 


#USArrests DATASET by Md Mujahedul Islam 
I have used the example dataset set up within R called "USArrests" that provides data on the  number of arrests for murder, assault, and rape for each of the 50 states in the United States in year 1973. It also provides data on the how many people of a particular state in percentage live in an urban area. There are thus in total 4 variables named 'assault, murder, rape and urbanpop' and 50 rows that contain the names of each states. You would find the descriptive analysis of this **USArrests** dataset in the *r_source_dataset02.r* file. Besides, in the repository, there are some images that simply demonstrates finding coded at the *r_source_dataset02.r*. 



